version: "3.3"

services:
  nginx_proxy:
    image: nginx:latest
    depends_on:
        - api
    volumes:
        - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
        - 80:80
        - 443:443

  api:
    image: hello_api:latest